#!/usr/bin/env python3
"""daylog_summary.py — pull a day's stats from the Personale backend and write
an "Activity Summary" block into the Obsidian daily note.

Stdlib only; Python 3.9 compatible (runs under launchd via bin/personale daylog).

Usage:
    daylog_summary.py [YYYY-MM-DD] [--dry-run] [--vault-root PATH]

Defaults to the most recently completed work day (effective date with a
configurable day-start hour, minus one day). Idempotent: re-running replaces
the existing marker-delimited block in place. Never touches other content.
"""

import argparse
import datetime
import json
import os
import re
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, List, Optional

BASE_URL = os.environ.get("PERSONALE_BASE_URL", "http://localhost:8696")
MARKER_START = "<!-- personale:activity-summary:start -->"
MARKER_END = "<!-- personale:activity-summary:end -->"
DEFAULT_VAULT = "~/Documents/Obsidian/Abhinav"


def day_start_hour():
    # type: () -> int
    try:
        return int(os.environ.get("PERSONALE_DAY_START_HOUR", "4"))
    except ValueError:
        return 4


def default_date(now=None):
    # type: (Optional[datetime.datetime]) -> datetime.date
    """Most recently completed work day: effective date (today if hour >=
    dayStartHour else yesterday) minus one day."""
    if now is None:
        now = datetime.datetime.now()
    effective = now.date()
    if now.hour < day_start_hour():
        effective -= datetime.timedelta(days=1)
    return effective - datetime.timedelta(days=1)


def fetch(endpoint, date_str):
    # type: (str, str) -> Any
    qs = urllib.parse.urlencode({"date": date_str, "dayStartHour": day_start_hour()})
    url = "{}/api/stats/{}?{}".format(BASE_URL, endpoint, qs)
    with urllib.request.urlopen(url, timeout=10) as resp:
        return json.loads(resp.read().decode("utf-8"))


def fmt_duration(seconds):
    # type: (int) -> str
    seconds = int(seconds)
    h, rem = divmod(seconds, 3600)
    m = rem // 60
    if h > 0:
        return "{}h {}m".format(h, m)
    if m > 0:
        return "{}m".format(m)
    return "{}s".format(seconds)


def build_markdown(date_str, day, categories, interruptors, sessions, now=None):
    # type: (str, dict, List[dict], List[dict], List[dict], Optional[datetime.datetime]) -> str
    if now is None:
        now = datetime.datetime.now()
    lines = [MARKER_START, "## Activity Summary", ""]

    total = day.get("totalTrackedSeconds", 0)
    apps = day.get("apps", []) or []
    idle = day.get("idleSessionCount", 0)
    lines.append(
        "**Tracked:** {} across {} app{} · {} idle gap{}".format(
            fmt_duration(total),
            len(apps),
            "" if len(apps) == 1 else "s",
            idle,
            "" if idle == 1 else "s",
        )
    )
    lines.append("")

    if categories:
        parts = [
            "{} {}% ({})".format(c.get("category"), c.get("percent"), fmt_duration(c.get("totalSeconds", 0)))
            for c in categories[:5]
        ]
        lines.append("**Categories:** " + " · ".join(parts))
        lines.append("")

    if sessions:
        longest = max(sessions, key=lambda s: s.get("durationSeconds", 0))
        lines.append(
            "**Focus sessions:** {} — longest: {} {}–{} ({})".format(
                len(sessions),
                longest.get("name"),
                longest.get("startTime"),
                longest.get("endTime"),
                fmt_duration(longest.get("durationSeconds", 0)),
            )
        )
        lines.append("")

    if interruptors:
        parts = [
            "{} ({}×, {})".format(i.get("appName"), i.get("count"), fmt_duration(i.get("totalSeconds", 0)))
            for i in interruptors[:3]
        ]
        lines.append("**Top interruptors:** " + " · ".join(parts))
        lines.append("")

    lines.append("*Generated by Personale at {}*".format(now.replace(microsecond=0).isoformat()))
    lines.append(MARKER_END)
    return "\n".join(lines)


def write_into_note(vault_root, date_str, block):
    # type: (Path, str, str) -> Path
    daily_dir = vault_root / "Daily"
    daily_dir.mkdir(parents=True, exist_ok=True)
    note = daily_dir / "{}.md".format(date_str)

    if note.exists():
        content = note.read_text(encoding="utf-8")
        pattern = re.compile(
            re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END), re.DOTALL
        )
        if pattern.search(content):
            new_content = pattern.sub(lambda _m: block, content, count=1)
        else:
            new_content = content.rstrip("\n") + "\n\n" + block + "\n"
    else:
        new_content = block + "\n"

    # Atomic write: temp file in the same dir, then os.replace.
    fd, tmp_path = tempfile.mkstemp(dir=str(daily_dir), prefix=".daylog-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(new_content)
        os.replace(tmp_path, str(note))
    except BaseException:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    return note


def main(argv=None):
    # type: (Optional[List[str]]) -> int
    parser = argparse.ArgumentParser(
        description="Write Personale activity summary into the Obsidian daily note."
    )
    parser.add_argument("date", nargs="?", help="Day to summarize (YYYY-MM-DD); defaults to the most recently completed work day")
    parser.add_argument("--dry-run", action="store_true", help="Print markdown, write nothing")
    parser.add_argument(
        "--vault-root",
        default=os.environ.get("PERSONALE_VAULT_ROOT", DEFAULT_VAULT),
        help="Obsidian vault root (default: %(default)s; env PERSONALE_VAULT_ROOT)",
    )
    args = parser.parse_args(argv)

    if args.date:
        try:
            date_str = datetime.datetime.strptime(args.date, "%Y-%m-%d").strftime("%Y-%m-%d")
        except ValueError:
            print("error: invalid date '{}' (expected YYYY-MM-DD)".format(args.date), file=sys.stderr)
            return 2
    else:
        date_str = default_date().isoformat()

    try:
        day = fetch("day", date_str)
        categories = fetch("categories", date_str)
        interruptors = fetch("interruptors", date_str)
        sessions = fetch("sessions", date_str)
    except (urllib.error.URLError, OSError, ValueError) as e:
        print(
            "error: Personale backend unreachable at {} ({})".format(BASE_URL, e),
            file=sys.stderr,
        )
        return 1

    if not day.get("totalTrackedSeconds"):
        print("no data: zero tracked seconds for {} — nothing written".format(date_str), file=sys.stderr)
        return 0

    block = build_markdown(date_str, day, categories, interruptors, sessions)

    if args.dry_run:
        print(block)
        return 0

    vault_root = Path(args.vault_root).expanduser()
    note = write_into_note(vault_root, date_str, block)
    print("wrote activity summary for {} -> {}".format(date_str, note))
    return 0


if __name__ == "__main__":
    sys.exit(main())
